apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-svc
  namespace: spinnaker-app
spec:
  selector:
    app: hello-kubernetes
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 32328
  type: NodePort
