apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  namespace: example
spec:
  replicas: 6
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
      - image: index.docker.io/jsaraswathi/source-demo:latest
        name: hello-kubernetes
