name: "When a release tag is created, build and publish a new version of the container image"

on:

  push: 
    branches: [ main ]

jobs:

  build-and-push-container-image:

    runs-on: ubuntu-latest

    env:
      CONTAINER_REGISTRY: index.docker.io
      CONTAINER_IMAGE: jsaraswathi/source-demo
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      IMAGE_VERSION: ${{ github.sha }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build image and version variables
        run: |
          echo "IMAGE=$CONTAINER_REGISTRY/$CONTAINER_IMAGE" >> $GITHUB_ENV
          
      - name: Build image
        run: | 
          docker build --tag "$IMAGE:$IMAGE_VERSION" \
            --build-arg IMAGE_VERSION="$IMAGE_VERSION" \
            --build-arg IMAGE_CREATE_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" \
            --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`" \
            --file src/app/Dockerfile src/app
      - name: Create additional image tags
        run: |
          docker tag $IMAGE:$IMAGE_VERSION $IMAGE:latest 
          
      - name: Log into registry
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Push image and tags to registry
        run: |
          docker push $IMAGE:latest
          docker push $IMAGE:$IMAGE_VERSION
         

